// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiS-QDuFc2D_NuA5UKsfLIzkdbh7D4cdU',
    appId: '1:874850863381:web:c301c157d6cac62e15411c',
    messagingSenderId: '874850863381',
    projectId: 'chat-app-cce2d',
    authDomain: 'chat-app-cce2d.firebaseapp.com',
    storageBucket: 'chat-app-cce2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa46Q0wuigNfQhr9kADJwj-inFWxJ_j2g',
    appId: '1:874850863381:android:032459baedacd66415411c',
    messagingSenderId: '874850863381',
    projectId: 'chat-app-cce2d',
    storageBucket: 'chat-app-cce2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXXVnECUUhLWuE4R1z-nRf6uETMSPNHB4',
    appId: '1:874850863381:ios:c217e17be4615dcf15411c',
    messagingSenderId: '874850863381',
    projectId: 'chat-app-cce2d',
    storageBucket: 'chat-app-cce2d.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXXVnECUUhLWuE4R1z-nRf6uETMSPNHB4',
    appId: '1:874850863381:ios:c217e17be4615dcf15411c',
    messagingSenderId: '874850863381',
    projectId: 'chat-app-cce2d',
    storageBucket: 'chat-app-cce2d.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiS-QDuFc2D_NuA5UKsfLIzkdbh7D4cdU',
    appId: '1:874850863381:web:af8dc0353a292f9015411c',
    messagingSenderId: '874850863381',
    projectId: 'chat-app-cce2d',
    authDomain: 'chat-app-cce2d.firebaseapp.com',
    storageBucket: 'chat-app-cce2d.firebasestorage.app',
  );
}
